name: "Deploy latest draft release"
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
#  schedule:
#    - cron: '0 14 * * 1,3'

permissions: write-all

jobs:
  deploy-peru:
    name: Start Peru deployment
    runs-on: ubuntu-latest
    environment:
      name: Peru
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls -l
      - run: cd ..
      - run: pwd
      - run: ls -l
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Peru deployment
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-pe
  
  deploy-greece:
    name: Start Greece deployment
    runs-on: ubuntu-latest
    needs: deploy-peru
    environment:
      name: Greece
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Greece deployment
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-gr
