name: "Deploy latest draft release"
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
#  schedule:
#    - cron: '0 14 * * 1,3'

permissions: write-all

jobs:
  deployment:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: Peru
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install ergo
        run: |
          go install github.com/beatlabs/ergo/cmd/cli@latest
          mv ~/go/bin/cli ~/go/bin/ergo

      - name: Fill in access-token in .ergo.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: '.ergo.yml'
        env:
          github.access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move .ergo.yml to ~/
        run: mv .ergo.yml ~/

      - name: Start deployment
        run: ergo deploy --publish-draft --skip-confirmation --releaseInterval 5m --owner nstratos --repo deploy --branches release-pe
