name: "Deploy latest draft release"
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
#  schedule:
#    - cron: '0 14 * * 1,3'

permissions: write-all

jobs:
  publish-latest-draft:
    name: Publish latest draft release
    runs-on: ubuntu-latest
    steps:
    - name: Get latest draft release
      id: last_release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: "prerelease"
        view_top: 1

    - run: |
        echo "Will attempt to publish the following release, if it's a draft:"
        echo "id: ${{ steps.last_release.outputs.id }}"
        echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
        echo "created_at: ${{ steps.last_release.outputs.created_at }}"
        echo "draft: ${{ steps.last_release.outputs.draft }}"

    - name: Publish draft release
      if: steps.last_release.outputs.draft == true
      uses: eregon/publish-release@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.last_release.outputs.id }}

  deploy-ar:
    name: Start deployment for Argentina
    runs-on: ubuntu-latest
    needs: publish-latest-draft
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-ar

  deploy-mx:
    name: Start deployment for Mexico
    runs-on: ubuntu-latest
    needs: deploy-ar
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-mx

  deploy-cl:
    name: Start deployment for Chile
    runs-on: ubuntu-latest
    needs: deploy-mx
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-cl

  deploy-co:
    name: Start deployment for Colombia
    runs-on: ubuntu-latest
    needs: deploy-cl
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-co

  deploy-pe:
    name: Start deployment for Peru
    runs-on: ubuntu-latest
    needs: deploy-co
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-pe

  deploy-gr:
    name: Start Greece deployment
    runs-on: ubuntu-latest
    needs: deploy-pe
    environment:
      name: Production
    steps:
      - name: Check out Rest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-ergo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deployment with ergo
        run: ergo deploy --skip-confirmation --owner nstratos --repo deploy --branches release-gr
